---
- hosts: "webserver"
  remote_user: ec2-user
  become: true
  vars_files:
    - "vars/my_vars.yml"
  roles:
    - workshop.update
    - workshop.locale
    - workshop.timezone

  #tasks:                
  #  - name: ""
  #    file: 
