---
- name: "Script | Create dir"
  file: path=/opt/scripts state=directory mode=0755

- name: "Script | Copy file"
  template: src=statsd-agent.j2 dest=/opt/scripts/statsd-agent.py mode=0610 force=yes
#  notify: restart systemd

- name: "Script | start"
  command: /usr/bin/python /opt/scripts/statsd-agent.py
  async: 45
  poll: 0

